spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidsland
    driverClassName: org.postgresql.Driver
    username: pavel
    password: 15995153
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: jdbc:postgresql://localhost:5432/kidsland
    user: pavel
    password: 15995153
    change-log: classpath:liquibase/changelog/changelog-master.yaml
    enabled: false
  docker:
    compose:
      enabled: false
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs