spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidsland
    driverClassName: org.postgresql.Driver
    username: pavel
    password: 15995153
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: jdbc:postgresql://localhost:5432/kidsland
    user: pavel
    password: 15995153
    change-log: classpath:liquibase/changelog/changelog-master.yaml
    enabled: false