name: Backend CI

on:
  push:
    paths:
      - 'kidsland-be/**'
  pull_request:
    paths:
      - 'kidsland-be/**'

jobs:
  build-kidsland-be:
    name: Build kidsland-be
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13 # You can use any PostgreSQL version
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=5s --health-timeout=3s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password

